version: '2.1'

services:
  rd-user-profile-db:
    build:
      context: database
    image: hmcts/rd-user-profile-db
    container_name: rd-user-profile-db
    volumes:
      - rd-user-profile-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-dbuserprofile}"
    ports:
      - 5432:5432
volumes:
  rd-user-profile-db-volume:
