java:
  applicationPort: 8091
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_USERNAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    POSTGRES_NAME: "{{ .Values.postgresql.postgresqlUsername}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    POSTGRES_PORT: 5432
    LOGBACK_REQUIRE_ALERT_LEVEL: 'false'
    LOGBACK_REQUIRE_ERROR_CODE: 'false'
  image: 'https://hmctspublic.azurecr.io/hmcts/draft-store-service:latest'
  postgresql:
    image:
      tag: 10.7.0-r68
    postgresqlUsername: dbuserprofile
    postgresqlPassword: dbuserprofile
    postgresqlDatabase: dbuserprofile
    service:
      port: 5432
  keyVaults:
    "s2s":
      resourceGroup: rpe-service-auth-provider
      secrets:
        - microservicekey-rd-user-profile-api
    "rd":
      resourceGroup: rd
      secrets:
        - s2s-url
