java:
    # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    aadIdentityName: rd
    keyVaults:
      "s2s":
        resourceGroup: rpe-service-auth-provider
        secrets:
          - microservicekey-rd-user-profile-api
      "rd":
        resourceGroup: rd
        secrets:
          - s2s-url
          - user-profile-api-POSTGRES-DATABASE
          - user-profile-api-POSTGRES-HOST

